### ISSUE TITLE
Feature request: html from string/buffer

### ISSUE THREAD

**Issue by solshark** [cherfia/chromiumly#280]
Would be nice to be able to provide html for conversion to pdf from string/buffer, not via PathLike only.
In my case I need to convert bunch of small templates which generated in run-time.
As far as I understood from source, `html` param for `HtmlConverter` must be file, which means I need to store all my templates in temporary files and feed path to converter. Not a big deal but it means I need to make sure files to be removed after conversion.

**Comment by cherfia** [comment]
@solshark I appreciate your feedback, and I understand the convenience of being able to provide HTML directly as a `string` or `buffer`, rather than relying on file paths. However, the current implementation of the [HTML route](https://gotenberg.dev/docs/routes#html-file-into-pdf-route) in [Gotenberg](https://gotenberg.dev/) requires a file input for the HTML parameter. 
You might consider creating a GitHub issue on their [repository](https://github.com/gotenberg/gotenberg). If Gotenberg supports the idea, I would be more than willing to make the necessary updates to the library accordingly 👍

**Comment by solshark** [comment]
F.e. this is how it could be done with Axios + form-data: 

```typescrip
  async generatePdf(html: string): Promise<Buffer> {
    const form = new FormData();
    form.append('files[]', html, {
      filename: 'index.html',
    });
    const result = await lastValueFrom(
      this.httpService
        .post(
          `${this.configService.get(
            'GOTENBERG_ENDPOINT',
          )}/forms/chromium/convert/html`,
          form.getBuffer(),
          {
            headers: form.getHeaders(),
            responseType: 'arraybuffer',
          },
        )
        .pipe(map((response) => response.data)),
    );

    return result;
    // const htmlConverter = new HtmlConverter();
    // const buffer = await htmlConverter.convert({
    //   html: Stream.from(html),
    // });
    // return buffer;
  }
```

Please note `this.httpService` it's nothing but `axios` for nest.js wrapper to work with Observable.

**Comment by cherfia** [comment]
@solshark I now understand your point 😄 and absolutely, I'll integrate that

**Comment by cherfia** [comment]
@solshark Thanks once more for providing clarification and making a feature request. I have added the buffer support in version [2.4.0](https://github.com/cherfia/chromiumly/releases/tag/v2.4.0). Please test it out and let me know if it meets your needs 👍
