### ISSUE TITLE
Passing buffer data not support for some formats

### ISSUE THREAD

**Issue by satramcs** [cherfia/chromiumly#366]
Getting `cfb is not supported` error while trying to convert .doc (buffer) data to .pdf file format.

Also below formats are not supported
`doc, pot, pps, ppt, vsd, vsdx, xls`

- `doc, pot, pps, ppt, xls, vsd` - through cfb is not supported error
- `vsdx` - through zip is not supported error

Note: doc and all formats are working fine when provide the direct file path, only issue with buffer data

Sample code
```
const path = require("path");
const fs = require("fs");

const bufferData = fs.readFileSync(path.join(__dirname, "/resources/1.doc"));
async function main() {
    const { PDFEngine } = await import("chromiumly");
    const buffer = await PDFEngine.convert({
        files: [bufferData],
    });
    fs.writeFileSync(path.join(__dirname, "/resources/1.pdf"), buffer);
}

main().catch(function (e) {
    console.log("Error converting file: " + e);
});

// output: Error converting file: Error: cfb is not supported
```
When hardcoded and put the doc and other formats directly in below line then it's working fine.
src/libre-office/utils/libre-office.utils.ts 
![image](https://github.com/cherfia/chromiumly/assets/62286308/364e78da-6652-440a-8ff6-77e3e4ff8b91)

So kindly fix the buffer data issue.
Suggestion: May be you can provide the option to get the extension from user when it was a buffer data and get that extension in libre-office.utils.ts
```
const bufferData = fs.readFileSync(path.join(__dirname, "/resources/1.doc"));
async function main() {
    const { PDFEngine } = await import("chromiumly");
    const buffer = await PDFEngine.convert({
        files: [{data: bufferData, ext: 'doc'}],
    });
    fs.writeFileSync(path.join(__dirname, "/resources/1.pdf"), buffer);
}
```

**Comment by cherfia** [comment]
@satramcs, I appreciate your report once more 👏 . I'll investigate further since I rely on a third-party package [file-type](https://www.npmjs.com/package/file-type), to detect binary-based file formats by examining the buffer's magic number, and apparently the package does not support text-based formats. I'll update you once the issue has been resolved.

**Comment by cherfia** [comment]
@satramcs, by the way, version `3.0.0` includes some breaking changes. Specifically, I've separated `LibreOffice` from `PDFEngines`. From now on, instead of using `PDFEngine.convert()`, you should use `LibreOffice.convert()`. This update was essential to align with Gotenberg's routes, formerly known as modules.

**Comment by cherfia** [comment]
@satramcs I just released a new version with a fix for the issue you mentioned. I also went ahead and dropped the `file-type` dependency and used your suggestion. You can see the code changes [here](https://github.com/cherfia/chromiumly/commit/a0771109e5350dd736d2ff6207a94fd9541d1fed), and as I mentioned previously, you would need to use `LibreOffice` instead of `PDFEngine`.

For reference, here's what the code with your suggestion looked like:
```
const bufferData = fs.readFileSync(path.join(__dirname, "/resources/1.doc"));
async function main() {
    const { LibreOffice } = await import("chromiumly");
    const buffer = await LibreOffice.convert({
        files: [{data: bufferData, ext: 'doc'}],
    });
    fs.writeFileSync(path.join(__dirname, "/resources/1.pdf"), buffer);
}
```
